export enum FeatureLayerId {
  DAMAGE = 'DAMAGE_FEATURE_LAYER',
  ASSET_BOUNDARY = 'ASSET_BOUNDARY_FEATURE_LAYER',
  COMMON_FILES = 'COMMON_FILES_FEATURE_LAYER',
  MATTERPORT = 'MATTER_PORT_FEATURE_LAYER',
  ANNOTATION = 'ANNOTATION_FEATURE_LAYER',
  STATIONING = 'STATIONING_FEATURE_LAYER',
  EXTERNAL_DATA = 'EXTERNAL_DATA_FEATURE_LAYER',
  PANORAMA = 'PANORAMA_FEATURE_LAYER',
}
