export enum LayerType {
  LAYER_GROUP = 'LAYER_GROUP',
  WMS = 'WMS_LAYER',
  OGC_3D_TILES = 'OGC_3D_TILES_LAYER',
  HSPC = 'HSPC_LAYER',
  FEATURE = 'FEATURE_LAYER',
  LTS = 'LTS_LAYER',
  TMS = 'TMS_LAYER',
  WFS = 'WFS_LAYER',
  BING_MAP = 'BING_MAP_LAYER',
  KML = 'KML_LAYER',
}
