export enum WMSLayerId {
  HAMBURG = 'HAMBURG_WMS_LAYER',
  PEGELONLINE = 'PEGELONLINE_WMS_LAYER',
  BUNDESWASSERSTRASSEN = 'BUNDESWASSERSTRAESSEN_WMS_LAYER',
  KILOMETERMARKEN = 'KILOMETERMARKEN_WMS_LAYER',
  FLIESSRICHTUNG = 'FLIESSRICHTUNG_WMS_LAYER',
  GEWAESSERNAMEN = 'GEWAESSERNAMEN_WMS_LAYER',
  BOHRUNGEN = 'BOHRUNGEN_WMS_LAYER',
  INLANDENC = 'INLANDENC_WMS_LAYER',
  WIND = 'WIND_WMS_LAYER',
  BINGMAP = 'BINGMAP_WMS_LAYER',
}
